import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import {
  acquireDiff,
  canonicalizeDiff,
  classifyFileKind,
  computeCoverage,
  diffDigest,
  hasGeneratedHeader,
  isTestPath,
  parseDiffFiles,
  repoIdFromSlug,
} from './diff';

const SRC = `diff --git a/src/a.ts b/src/a.ts
index 111..222 100644
--- a/src/a.ts
+++ b/src/a.ts
@@ -1,2 +1,2 @@
-const a = 0;
+const a = 1;
 export { a };
`;

const LOCKFILE = `diff --git a/package-lock.json b/package-lock.json
index 333..444 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,1 +1,2 @@
+  "added": true
`;

const BINARY = `diff --git a/img.png b/img.png
index 555..666 100644
Binary files a/img.png and b/img.png differ
`;

describe('parseDiffFiles', () => {
  it('splits a multi-file diff into per-file sections with paths + line counts', () => {
    const files = parseDiffFiles(SRC + LOCKFILE + BINARY);
    expect(files.map((f) => f.path)).toEqual([
      'src/a.ts',
      'package-lock.json',
      'img.png',
    ]);
    const a = files[0];
    expect(a.added).toBe(1);
    expect(a.removed).toBe(1);
    expect(a.bytes).toBeGreaterThan(0);
  });

  it('detects a binary file section', () => {
    const [bin] = parseDiffFiles(BINARY);
    expect(bin.isBinary).toBe(true);
    expect(bin.kind).toBe('binary');
  });

  it('returns [] for an empty diff', () => {
    expect(parseDiffFiles('')).toEqual([]);
    expect(parseDiffFiles('   \n')).toEqual([]);
  });
});

describe('classifyFileKind', () => {
  it('classifies lockfiles / build output as generated', () => {
    expect(classifyFileKind('package-lock.json', false)).toBe('generated');
    expect(classifyFileKind('pnpm-lock.yaml', false)).toBe('generated');
    expect(classifyFileKind('dist/bundle.js', false)).toBe('generated');
    expect(classifyFileKind('app.min.js', false)).toBe('generated');
  });

  it('classifies generator OUTPUT as generated by unambiguous name (*.gen.*, *.pb.go, generated/, *_generated.*)', () => {
    for (const p of [
      'pkg/gen/api/api.gen.go',
      'proto/foo.pb.go',
      'src/__generated__/schema.ts',
      'lib/generated/client.ts',
      'app/types.generated.ts',
      'app/types_generated.py',
    ]) {
      expect(classifyFileKind(p, false), p).toBe('generated');
    }
    // The schema that DRIVES a generator is hand-written and must be reviewed.
    expect(classifyFileKind('pkg/services/actor/ent/schema/accounts.go', false)).toBe('source');
    // A bare `gen/` directory is NOT a generated marker: Go repos keep generator SOURCES there.
    expect(classifyFileKind('cmd/gen/main.go', false)).toBe('source');
    expect(classifyFileKind('tools/gen/templates/model.tmpl', false)).toBe('source');
    expect(classifyFileKind('src/general/index.ts', false)).toBe('source');
  });

  // A `generated` omission never disqualifies a receipt, so the header rule must fail CLOSED:
  // it may only fire on the file's own first line, never on a mention further down.
  it('classifies a file whose diff shows a generator header on line 1 as generated', () => {
    const newFile = `diff --git a/pkg/services/x/gen/ent/client.go b/pkg/services/x/gen/ent/client.go
new file mode 100644
--- /dev/null
+++ b/pkg/services/x/gen/ent/client.go
@@ -0,0 +1,3 @@
+// Code generated by ent, DO NOT EDIT.
+
+package ent
`;
    const topEdit = `diff --git a/src/api/types.ts b/src/api/types.ts
--- a/src/api/types.ts
+++ b/src/api/types.ts
@@ -1,4 +1,4 @@
-/* @generated by orval v6 */
+/* @generated by orval v7 */
 export type A = string;
`;
    expect(classifyFileKind('pkg/services/x/gen/ent/client.go', false, newFile)).toBe('generated');
    expect(classifyFileKind('src/api/types.ts', false, topEdit)).toBe('generated');
    expect(hasGeneratedHeader(newFile)).toBe(true);
  });

  it('keeps a mid-file hunk of a generated file, and a template that MENTIONS the marker, as source', () => {
    const midFile = `diff --git a/pkg/services/x/gen/ent/client.go b/pkg/services/x/gen/ent/client.go
--- a/pkg/services/x/gen/ent/client.go
+++ b/pkg/services/x/gen/ent/client.go
@@ -40,3 +40,4 @@ func (c *Client) init() {
 	c.Account = NewAccountClient(c.config)
+	c.Portfolio = NewPortfolioClient(c.config)
 }
`;
    const template = `diff --git a/tools/gen/templates/header.tmpl b/tools/gen/templates/header.tmpl
--- a/tools/gen/templates/header.tmpl
+++ b/tools/gen/templates/header.tmpl
@@ -1,3 +1,3 @@
 {{define "header"}}
-// Code generated by tools/gen. DO NOT EDIT.
+// Code generated by tools/gen, DO NOT EDIT.
 {{end}}
`;
    expect(classifyFileKind('pkg/services/x/gen/ent/client.go', false, midFile)).toBe('source');
    expect(classifyFileKind('tools/gen/templates/header.tmpl', false, template)).toBe('source');
    // parseDiffFiles feeds the section through, so the same verdicts hold end to end.
    expect(parseDiffFiles(midFile + template).map((f) => f.kind)).toEqual(['source', 'source']);
  });

  it('classifies ordinary code as source', () => {
    expect(classifyFileKind('src/a.ts', false)).toBe('source');
    expect(classifyFileKind('lib/util.py', false)).toBe('source');
  });

  it('classifies anything binary as binary, regardless of path', () => {
    expect(classifyFileKind('src/a.ts', true)).toBe('binary');
  });
});

describe('computeCoverage', () => {
  it('includes source, omits generated + binary — and NAMES every omission (no silent drop)', () => {
    const files = parseDiffFiles(SRC + LOCKFILE + BINARY);
    const { coverage, includedDiff } = computeCoverage(files);
    expect(coverage.totalFiles).toBe(3);
    expect(coverage.includedFiles).toBe(1);
    expect(coverage.omittedFiles).toBe(2);
    const omitted = coverage.files.filter((f) => !f.included);
    expect(omitted.map((f) => [f.path, f.omitReason]).sort()).toEqual([
      ['img.png', 'binary'],
      ['package-lock.json', 'generated'],
    ]);
    // the included diff is exactly the source section (the reviewer sees only it)
    expect(includedDiff).toContain('src/a.ts');
    expect(includedDiff).not.toContain('package-lock.json');
  });

  it('omits a source file as over-limit (NAMED) when the byte ceiling is exceeded', () => {
    const big = `diff --git a/src/big.ts b/src/big.ts
@@ -1,1 +1,1 @@
+${'x'.repeat(500)}
`;
    const files = parseDiffFiles(SRC + big);
    // ceiling fits the first source file but not both → second is over-limit
    const { coverage } = computeCoverage(files, 200);
    const over = coverage.files.find((f) => f.path === 'src/big.ts');
    expect(over?.included).toBe(false);
    expect(over?.omitReason).toBe('over-limit');
    expect(over?.kind).toBe('source'); // an omitted SOURCE file → disqualifies a receipt
  });

  it('always includes the first file even if it alone exceeds the ceiling (never drops everything)', () => {
    const { coverage } = computeCoverage(parseDiffFiles(SRC), 1);
    expect(coverage.includedFiles).toBe(1);
  });

  const TEST_FILE = `diff --git a/src/a.test.ts b/src/a.test.ts
@@ -1,1 +1,1 @@
+${'t'.repeat(150)}
`;
  const SOURCE_FILE = `diff --git a/src/b.ts b/src/b.ts
@@ -1,1 +1,1 @@
+${'s'.repeat(150)}
`;

  it('admits non-test source before tests when the ceiling binds, keeping entries in diff order', () => {
    // The test file comes FIRST in diff order; a path-order budget would admit it and omit the change.
    const files = parseDiffFiles(TEST_FILE + SOURCE_FILE);
    const { coverage, includedDiff } = computeCoverage(files, 200);
    expect(coverage.files.map((f) => f.path)).toEqual(['src/a.test.ts', 'src/b.ts']);
    expect(coverage.files.find((f) => f.path === 'src/b.ts')?.included).toBe(true);
    const test = coverage.files.find((f) => f.path === 'src/a.test.ts');
    expect(test?.included).toBe(false);
    expect(test?.omitReason).toBe('over-limit');
    expect(test?.kind).toBe('source'); // a test is still source — its omission still disqualifies
    expect(includedDiff).toContain('src/b.ts');
    expect(includedDiff).not.toContain('src/a.test.ts');
  });

  it('tests fill whatever budget the source leaves, in diff order', () => {
    const files = parseDiffFiles(TEST_FILE + SOURCE_FILE);
    const { coverage, includedDiff } = computeCoverage(files, 10_000);
    expect(coverage.includedFiles).toBe(2);
    expect(includedDiff.indexOf('src/a.test.ts')).toBeLessThan(includedDiff.indexOf('src/b.ts'));
  });
});

describe('isTestPath', () => {
  it('recognizes the common test-file shapes', () => {
    for (const p of [
      'pkg/services/finance/dto_test.go',
      'src/core/spawn.test.ts',
      'src/lib/fire.spec.tsx',
      'tests/integration/api.py',
      'app/__tests__/home.test.tsx',
      'scripts/tests/migrate.bats',
      'src/test_models.py',
    ]) {
      expect(isTestPath(p), p).toBe(true);
    }
  });

  it('leaves ordinary source alone', () => {
    for (const p of ['pkg/services/finance/dto.go', 'src/core/spawn.ts', 'src/contest/index.ts']) {
      expect(isTestPath(p), p).toBe(false);
    }
  });
});

describe('canonicalizeDiff + diffDigest', () => {
  it('is stable across CRLF and trailing-newline noise', () => {
    const lf = 'a\nb\n';
    const crlf = 'a\r\nb\r\n\n\n';
    expect(canonicalizeDiff(crlf)).toBe(canonicalizeDiff(lf));
    expect(diffDigest(crlf)).toBe(diffDigest(lf));
  });

  it('is a sha256:-prefixed digest, distinct for distinct content', () => {
    expect(diffDigest(SRC)).toMatch(/^sha256:[0-9a-f]{64}$/);
    expect(diffDigest(SRC)).not.toBe(diffDigest(LOCKFILE));
  });
});

describe('repoIdFromSlug', () => {
  it('produces the same normal form resolveRepoId derives from a github remote', () => {
    // resolveRepoId normalizes `git@github.com:o/r.git` → `https://github.com/o/r`;
    // the slug form must land on the identical string or the receipt key splits.
    expect(repoIdFromSlug('o/r')).toBe('https://github.com/o/r');
  });
});

describe('acquireDiff — repo identity', () => {
  // A non-repo cwd, standing in for a caller that fires a URL-PR review from an
  // unrelated directory (a dashboard's data dir, /tmp, CI scratch space).
  let cwd: string;
  beforeEach(() => {
    cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'ensemble-diff-repoid-'));
  });
  afterEach(() => {
    fs.rmSync(cwd, { force: true, recursive: true });
  });

  it('repoIdOverride keys the identity to the reviewed repo, not the cwd', () => {
    const acquired = acquireDiff({
      cwd,
      diffMode: 'pr',
      diffText: SRC,
      repoIdOverride: repoIdFromSlug('LiskHQ/lisk-web'),
    });
    expect(acquired.repoId).toBe('https://github.com/LiskHQ/lisk-web');
  });

  it('without an override, falls back to the cwd-derived identity (null in a non-repo)', () => {
    const acquired = acquireDiff({ cwd, diffMode: 'pr', diffText: SRC });
    expect(acquired.repoId).toBeNull();
  });
});
