import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import type { SandboxProfileRef } from '../modes/review/evidence';

// THE CODEX WRAPPER PROFILE — an ensemble-OWNED external sandbox that gives the codex seat the
// worktree without giving it the disk (spec §2).
//
// WHY A WRAPPER: codex's own `-s read-only` restricts WRITES, not READS — a `read-only` codex
// still reads anything on disk (openai/codex#5237; no read-scoping option exists). Grok already
// solves this with a kernel profile (`ensemble-review`), so we do the same for codex from the
// outside: `sandbox-exec -f <profile> codex exec … --dangerously-bypass-approvals-and-sandbox`.
// The bypass flag disables codex's INTERNAL sandbox because nested Seatbelt does not compose —
// its own docs say the flag is "intended solely for running in environments that are externally
// sandboxed", which is exactly this. The EXTERNAL profile is the boundary.
//
// HONEST CONTAINMENT (gate-r3 pin 3) — verified empirically on macOS 15, 2026-07-09:
//   · Exec of ANY path inside the worktree is DENIED by the kernel (a planted binary and a
//     planted `#!/bin/sh` script both fail EPERM; an identical script outside the worktree in a
//     read-allowed dir execs fine, so the denial is this rule and not codesigning).
//   · BUT a shell-capable agent can still INTERPRET an untrusted file as DATA: `sh
//     <worktree>/evil.sh` runs, because it execs /bin/sh and merely READS the script. No-exec
//     narrows the vector; it does not close it. The real boundary is the rest of the profile —
//     no writes outside ~/.codex and the OS temp dir, no reads of any credential outside
//     ~/.codex, and no network except TCP 443.
//   · NETWORK IS PORT-SCOPED, NOT PER-HOST. Seatbelt cannot express a DNS-host allowlist:
//     `(remote host …)` is an unbound variable and `(remote tcp "api.openai.com:443")` is
//     rejected with "host must be * or localhost". So the spec's per-HOST vendor-API intent is
//     NOT achievable in Seatbelt; `(remote ip "*:443")` is the tightest the platform allows.
//     A true per-host fence needs an egress proxy — deliberately out of v1, and NOT claimed here.
//
// Any change to the rules below MUST bump `version` — a receipt minted under a weaker profile
// must never verify as equivalent to one minted under a tighter one (evidence.ts).
export const CODEX_SANDBOX_PROFILE: SandboxProfileRef = {
  id: 'ensemble-review-codex',
  version: 1,
};

// Read-allowed system roots. Deny-by-default means everything absent from this list — every
// credential in $HOME, every other repo on disk — is kernel-unreadable to the seat.
const SYSTEM_READ_ROOTS = [
  '/usr',
  '/bin',
  '/sbin',
  '/System',
  '/Library',
  '/opt/homebrew',
  '/private/var',
  '/private/etc',
  '/private/tmp',
  '/dev',
];

function sbSubpaths(paths: string[]): string {
  return paths.map((p) => `(subpath ${JSON.stringify(p)})`).join(' ');
}

export interface CodexSandboxPaths {
  // The codex CLI's own auth/config — the seat must read its own credential to call its API.
  codexHome: string;
  // Where node + the codex install live (resolved from the running node, not guessed).
  nodePrefix: string;
  // The worktree root, ALREADY REALPATH'd. Seatbelt matches resolved paths, so a
  // `/tmp/...` (symlink to `/private/tmp/...`) subpath rule silently matches nothing.
  worktree: string;
}

// PURE: the exact SBPL text. Encoded as data so a unit test pins every rule — a silent drop
// here is the difference between a sandbox and a costume.
export function renderCodexSandboxProfile(p: CodexSandboxPaths): string {
  return `(version 1)
;; ensemble-review-codex v${CODEX_SANDBOX_PROFILE.version} — generated by ensemble-ai. Do not hand-edit.
;; Deny-by-default. The codex seat may read the PR worktree + its own auth, and nothing else.
;; Containment caveat: exec of worktree paths is denied, but a shell can still read an
;; untrusted file as DATA ("sh <worktree>/x.sh"). The write/secret/network fences are the
;; real boundary, not this exec rule. Network is PORT-scoped (443) — Seatbelt cannot
;; express a per-host DNS allowlist.
(deny default)
(import "/System/Library/Sandbox/Profiles/bsd.sb")
(allow process-fork)
(allow process-exec)
;; Never EXECUTE untrusted PR content (gate-r3 pin 3). Last match wins in SBPL, so this
;; deny overrides the blanket process-exec above.
(deny process-exec (subpath ${JSON.stringify(p.worktree)}))
(allow process-info*)
(allow file-map-executable)
(allow ipc-posix-shm*)
(allow sysctl-read)
(allow mach-lookup)
(allow signal)
(allow file-read-metadata)
(allow file-read* ${sbSubpaths(SYSTEM_READ_ROOTS)})
(allow file-read* (subpath ${JSON.stringify(p.nodePrefix)}))
(allow file-read* (subpath ${JSON.stringify(p.worktree)}))
(allow file-read* (subpath ${JSON.stringify(p.codexHome)}))
(allow file-write* (subpath ${JSON.stringify(p.codexHome)}) (subpath "/private/tmp") (subpath "/dev"))
(allow network-outbound (remote ip "*:443") (remote ip "*:53") (remote unix-socket))
(allow network-inbound (local ip "*:*"))
`;
}

// The platform check. Seatbelt is macOS-only; Landlock (Linux) cannot express these read rules
// today. Anywhere else the seat FAILS CLOSED to the packet — never silently to a naked codex.
export function codexSandboxSupported(platform = process.platform): boolean {
  return platform === 'darwin' && fs.existsSync('/usr/bin/sandbox-exec');
}

export function defaultCodexSandboxPaths(worktree: string): CodexSandboxPaths {
  return {
    codexHome: path.join(os.homedir(), '.codex'),
    // process.execPath is <prefix>/bin/node → <prefix> covers node AND the codex install
    // that sits beside it in the same nvm/npm prefix.
    nodePrefix: path.dirname(path.dirname(fs.realpathSync(process.execPath))),
    worktree: fs.realpathSync(worktree),
  };
}

// Write the profile 0600 into an owner-only temp dir and return its path.
export function writeCodexSandboxProfile(paths: CodexSandboxPaths): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ensemble-sb-'));
  fs.chmodSync(dir, 0o700);
  const file = path.join(dir, 'ensemble-review-codex.sb');
  fs.writeFileSync(file, renderCodexSandboxProfile(paths), { mode: 0o600 });
  fs.chmodSync(file, 0o600);
  return file;
}

// PURE: wrap a command in `sandbox-exec -f <profile>`. The wrapped argv is what actually runs.
export function wrapWithSandbox(
  profileFile: string,
  bin: string,
  args: string[]
): { args: string[]; bin: string } {
  return { args: ['-f', profileFile, bin, ...args], bin: '/usr/bin/sandbox-exec' };
}

// PURE: the codex argv for a WORKTREE-mode review. Differs from the packet argv in exactly two
// ways: the internal sandbox is off (the external profile governs — nested Seatbelt does not
// compose) and the cwd is the worktree (so codex's file tools reach the project). `-o <file>`
// still carries the reply, as in packet mode.
export function buildCodexWorktreeArgs(
  config: { effort: string; model: string },
  outFile: string,
  prompt: string
): string[] {
  return [
    'exec',
    '--skip-git-repo-check',
    '--ephemeral',
    '--color',
    'never',
    '--dangerously-bypass-approvals-and-sandbox',
    '-m',
    config.model,
    '-c',
    `model_reasoning_effort="${config.effort}"`,
    '-o',
    outFile,
    prompt,
  ];
}
